# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         NNML
version:      1.14
version_from: 
installdirs:  site
requires:
    IO::File:                      0
    IO::Select:                    0
    IO::Socket:                    1.13
    Net::Cmd:                      2.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
